//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regularity_Rally.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Regularity_Rally.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign points.
        /// </summary>
        internal static string adc_assignpoints_category_btn {
            get {
                return ResourceManager.GetString("adc_assignpoints_category_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string adc_brands_title {
            get {
                return ResourceManager.GetString("adc_brands_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string adc_cancel_category_btn_ {
            get {
                return ResourceManager.GetString("adc_cancel_category_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string adc_cancel_com_btn_ {
            get {
                return ResourceManager.GetString("adc_cancel_com_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string adc_cat_title {
            get {
                return ResourceManager.GetString("adc_cat_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string adc_catPoints_title {
            get {
                return ResourceManager.GetString("adc_catPoints_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient.
        /// </summary>
        internal static string adc_coef_cut_points_racerscategory_label {
            get {
                return ResourceManager.GetString("adc_coef_cut_points_racerscategory_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring positions.
        /// </summary>
        internal static string adc_CountOfPosition_racerscategory_label_ {
            get {
                return ResourceManager.GetString("adc_CountOfPosition_racerscategory_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string adc_delete_category_btn {
            get {
                return ResourceManager.GetString("adc_delete_category_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string adc_min_racerscategory_label {
            get {
                return ResourceManager.GetString("adc_min_racerscategory_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string adc_name_category_label {
            get {
                return ResourceManager.GetString("adc_name_category_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string adc_place_category_label {
            get {
                return ResourceManager.GetString("adc_place_category_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string adc_points_category_label {
            get {
                return ResourceManager.GetString("adc_points_category_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string adc_save_category_btn {
            get {
                return ResourceManager.GetString("adc_save_category_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ancar_cancel_car_btn_ {
            get {
                return ResourceManager.GetString("ancar_cancel_car_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add car.
        /// </summary>
        internal static string ancar_car_title {
            get {
                return ResourceManager.GetString("ancar_car_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ancar_delete_car_btn_ {
            get {
                return ResourceManager.GetString("ancar_delete_car_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ancar_delete_team_btn_ {
            get {
                return ResourceManager.GetString("ancar_delete_team_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ancar_email_team_label_ {
            get {
                return ResourceManager.GetString("ancar_email_team_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string ancar_model_car_label_ {
            get {
                return ResourceManager.GetString("ancar_model_car_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string ancar_name_car_label_ {
            get {
                return ResourceManager.GetString("ancar_name_car_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ancar_name_team_label_ {
            get {
                return ResourceManager.GetString("ancar_name_team_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ancar_save_car_btn_ {
            get {
                return ResourceManager.GetString("ancar_save_car_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ancar_save_team_btn_ {
            get {
                return ResourceManager.GetString("ancar_save_team_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string ancar_short_team_label_ {
            get {
                return ResourceManager.GetString("ancar_short_team_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string ancar_team_title {
            get {
                return ResourceManager.GetString("ancar_team_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        internal static string ancar_vin_car_label_ {
            get {
                return ResourceManager.GetString("ancar_vin_car_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ancar_year_car_label_ {
            get {
                return ResourceManager.GetString("ancar_year_car_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string anm_Address_com_label_ {
            get {
                return ResourceManager.GetString("anm_Address_com_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string anm_delete_com_btn {
            get {
                return ResourceManager.GetString("anm_delete_com_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string anm_email_com_label {
            get {
                return ResourceManager.GetString("anm_email_com_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string anm_name_com_label {
            get {
                return ResourceManager.GetString("anm_name_com_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string anm_save_com_btn {
            get {
                return ResourceManager.GetString("anm_save_com_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string anm_tel_com_label_ {
            get {
                return ResourceManager.GetString("anm_tel_com_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string anm_web_com_label {
            get {
                return ResourceManager.GetString("anm_web_com_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add racer.
        /// </summary>
        internal static string anr_add_racer_btn_ {
            get {
                return ResourceManager.GetString("anr_add_racer_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string anr_cancel_race_btn_ {
            get {
                return ResourceManager.GetString("anr_cancel_race_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string anr_date_race_label {
            get {
                return ResourceManager.GetString("anr_date_race_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string anr_delete_race_btn_ {
            get {
                return ResourceManager.GetString("anr_delete_race_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove racer.
        /// </summary>
        internal static string anr_delete_racer_btn_ {
            get {
                return ResourceManager.GetString("anr_delete_racer_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string anr_length_race_label {
            get {
                return ResourceManager.GetString("anr_length_race_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string anr_location_race_label {
            get {
                return ResourceManager.GetString("anr_location_race_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure company.
        /// </summary>
        internal static string anr_meascom_race_label {
            get {
                return ResourceManager.GetString("anr_meascom_race_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string anr_name_race_label {
            get {
                return ResourceManager.GetString("anr_name_race_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string anr_name_racer_header {
            get {
                return ResourceManager.GetString("anr_name_racer_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string anr_race_title {
            get {
                return ResourceManager.GetString("anr_race_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string anr_save_race_btn_ {
            get {
                return ResourceManager.GetString("anr_save_race_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string anr_start_num_header {
            get {
                return ResourceManager.GetString("anr_start_num_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string anr_state_race_label {
            get {
                return ResourceManager.GetString("anr_state_race_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string anr_team_racer_header {
            get {
                return ResourceManager.GetString("anr_team_racer_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user to brand.
        /// </summary>
        internal static string autb_users_title {
            get {
                return ResourceManager.GetString("autb_users_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New car.
        /// </summary>
        internal static string car_addcar_btn_ {
            get {
                return ResourceManager.GetString("car_addcar_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string car_brandcar_head {
            get {
                return ResourceManager.GetString("car_brandcar_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string car_car_title {
            get {
                return ResourceManager.GetString("car_car_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string car_closecar_btn_ {
            get {
                return ResourceManager.GetString("car_closecar_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string car_closecat_btn_ {
            get {
                return ResourceManager.GetString("car_closecat_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string car_model_head {
            get {
                return ResourceManager.GetString("car_model_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        internal static string car_vin_head {
            get {
                return ResourceManager.GetString("car_vin_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string car_year_head {
            get {
                return ResourceManager.GetString("car_year_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string cat_cat_title {
            get {
                return ResourceManager.GetString("cat_cat_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        internal static string category_addcat_btn_ {
            get {
                return ResourceManager.GetString("category_addcat_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient.
        /// </summary>
        internal static string category_coefcategory_head {
            get {
                return ResourceManager.GetString("category_coefcategory_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string category_limitcategory_head {
            get {
                return ResourceManager.GetString("category_limitcategory_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category_namecategory_head {
            get {
                return ResourceManager.GetString("category_namecategory_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string category_points_head {
            get {
                return ResourceManager.GetString("category_points_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string category_positionpoints_head {
            get {
                return ResourceManager.GetString("category_positionpoints_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connection.
        /// </summary>
        internal static string DF_Device_connection {
            get {
                return ResourceManager.GetString("DF_Device_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DF_Status_label {
            get {
                return ResourceManager.GetString("DF_Status_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score board connection.
        /// </summary>
        internal static string DF_Table_connection {
            get {
                return ResourceManager.GetString("DF_Table_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-ons.
        /// </summary>
        internal static string hs_Add_ons_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Add_ons_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paddock.
        /// </summary>
        internal static string hs_Add_ons_Paddock_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Add_ons_Paddock_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        internal static string hs_Add_ons_Reporter_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Add_ons_Reporter_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string hs_Events_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Events_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string hs_Events_Races_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Events_Races_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        internal static string hs_Events_Tournaments_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Events_Tournaments_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurer brands.
        /// </summary>
        internal static string hs_Items__Measurerbrands_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items__Measurerbrands_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string hs_Items_Cars_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_Cars_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string hs_Items_Category_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_Category_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string hs_Items_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racers.
        /// </summary>
        internal static string hs_Items_Racers_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_Racers_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string hs_Items_Races_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_Races_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string hs_Items_Teams_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_Teams_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        internal static string hs_Items_Tournaments_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_Tournaments_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string hs_Items_Users_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Items_Users_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laps.
        /// </summary>
        internal static string hs_LapsOfRace_label_ {
            get {
                return ResourceManager.GetString("hs_LapsOfRace_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string hs_Logout_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Logout_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string hs_Settings_Device_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Settings_Device_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string hs_Settings_Language_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Settings_Language_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string hs_Settings_MenuItemHeader {
            get {
                return ResourceManager.GetString("hs_Settings_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to database.
        /// </summary>
        internal static string lw_connectdbs_btn {
            get {
                return ResourceManager.GetString("lw_connectdbs_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lw_login_btn {
            get {
                return ResourceManager.GetString("lw_login_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lw_login_label {
            get {
                return ResourceManager.GetString("lw_login_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lw_password_label {
            get {
                return ResourceManager.GetString("lw_password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New brand.
        /// </summary>
        internal static string measurerbrand_addbrand_btn_ {
            get {
                return ResourceManager.GetString("measurerbrand_addbrand_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string measurerbrand_Address_head {
            get {
                return ResourceManager.GetString("measurerbrand_Address_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string measurerbrand_brand_head {
            get {
                return ResourceManager.GetString("measurerbrand_brand_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string measurerbrand_closebrand_btn_ {
            get {
                return ResourceManager.GetString("measurerbrand_closebrand_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string measurerbrand_Email_head {
            get {
                return ResourceManager.GetString("measurerbrand_Email_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurer brands.
        /// </summary>
        internal static string measurerbrand_meas_title {
            get {
                return ResourceManager.GetString("measurerbrand_meas_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string measurerbrand_Telephone_head {
            get {
                return ResourceManager.GetString("measurerbrand_Telephone_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string measurerbrand_Web_head {
            get {
                return ResourceManager.GetString("measurerbrand_Web_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        internal static string mwi_AddNote_btn_ {
            get {
                return ResourceManager.GetString("mwi_AddNote_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string mwi_AddRace_ {
            get {
                return ResourceManager.GetString("mwi_AddRace_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born.
        /// </summary>
        internal static string mwi_Born_nameRacer_head {
            get {
                return ResourceManager.GetString("mwi_Born_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string mwi_Car_nameRacer_head {
            get {
                return ResourceManager.GetString("mwi_Car_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string mwi_choose_race_btn_ {
            get {
                return ResourceManager.GetString("mwi_choose_race_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string mwi_CloseRace_ {
            get {
                return ResourceManager.GetString("mwi_CloseRace_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string mwi_Date_head {
            get {
                return ResourceManager.GetString("mwi_Date_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legth.
        /// </summary>
        internal static string mwi_Length_head {
            get {
                return ResourceManager.GetString("mwi_Length_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mDate.
        /// </summary>
        internal static string mwi_Mdate_head {
            get {
                return ResourceManager.GetString("mwi_Mdate_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure brand.
        /// </summary>
        internal static string mwi_Meas_head {
            get {
                return ResourceManager.GetString("mwi_Meas_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwi_name_nameRacer_head {
            get {
                return ResourceManager.GetString("mwi_name_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string mwi_Nationality_nameRacer_head {
            get {
                return ResourceManager.GetString("mwi_Nationality_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string mwi_note_racerdetail_head {
            get {
                return ResourceManager.GetString("mwi_note_racerdetail_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string mwi_Place_head {
            get {
                return ResourceManager.GetString("mwi_Place_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string mwi_race_title {
            get {
                return ResourceManager.GetString("mwi_race_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racers.
        /// </summary>
        internal static string mwi_racers_lbl {
            get {
                return ResourceManager.GetString("mwi_racers_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference time.
        /// </summary>
        internal static string mwi_referencetime_lbl {
            get {
                return ResourceManager.GetString("mwi_referencetime_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference time.
        /// </summary>
        internal static string mwi_Reftime_nameRacer_head {
            get {
                return ResourceManager.GetString("mwi_Reftime_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string mwi_Status_head {
            get {
                return ResourceManager.GetString("mwi_Status_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string mwi_Team_nameRacer_head {
            get {
                return ResourceManager.GetString("mwi_Team_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time keeping.
        /// </summary>
        internal static string mwi_Timekeeping_btn {
            get {
                return ResourceManager.GetString("mwi_Timekeeping_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string mwi_Title_head {
            get {
                return ResourceManager.GetString("mwi_Title_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string mwrs_Add_lbl {
            get {
                return ResourceManager.GetString("mwrs_Add_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new race.
        /// </summary>
        internal static string mwrs_add_new_btn {
            get {
                return ResourceManager.GetString("mwrs_add_new_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mwrs_cancel_lbl {
            get {
                return ResourceManager.GetString("mwrs_cancel_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string mwrs_Car {
            get {
                return ResourceManager.GetString("mwrs_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string mwrs_car_RacerInRace {
            get {
                return ResourceManager.GetString("mwrs_car_RacerInRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string mwrs_cat_lbl {
            get {
                return ResourceManager.GetString("mwrs_cat_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose race.
        /// </summary>
        internal static string mwrs_chooserace_label_ {
            get {
                return ResourceManager.GetString("mwrs_chooserace_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final time.
        /// </summary>
        internal static string mwrs_finaltime_RacerInRace {
            get {
                return ResourceManager.GetString("mwrs_finaltime_RacerInRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string mwrs_length_lbl {
            get {
                return ResourceManager.GetString("mwrs_length_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwrs_name_racer_lbl {
            get {
                return ResourceManager.GetString("mwrs_name_racer_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string mwrs_name_team_lbl {
            get {
                return ResourceManager.GetString("mwrs_name_team_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwrs_name_timekeep_lbl {
            get {
                return ResourceManager.GetString("mwrs_name_timekeep_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwrs_nameofrace_lbl {
            get {
                return ResourceManager.GetString("mwrs_nameofrace_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. of racers.
        /// </summary>
        internal static string mwrs_numofracers_lbl {
            get {
                return ResourceManager.GetString("mwrs_numofracers_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalization.
        /// </summary>
        internal static string mwrs_pentime_RacerInRace {
            get {
                return ResourceManager.GetString("mwrs_pentime_RacerInRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string mwrs_place_lbl {
            get {
                return ResourceManager.GetString("mwrs_place_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string mwrs_place_timekeep_lbl {
            get {
                return ResourceManager.GetString("mwrs_place_timekeep_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string mwrs_pos_RacerInRace {
            get {
                return ResourceManager.GetString("mwrs_pos_RacerInRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string mwrs_Position {
            get {
                return ResourceManager.GetString("mwrs_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string mwrs_print {
            get {
                return ResourceManager.GetString("mwrs_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racer.
        /// </summary>
        internal static string mwrs_racer {
            get {
                return ResourceManager.GetString("mwrs_racer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racers.
        /// </summary>
        internal static string mwrs_racers_lbl {
            get {
                return ResourceManager.GetString("mwrs_racers_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string mwrs_Remove_lbl {
            get {
                return ResourceManager.GetString("mwrs_Remove_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mwrs_save_lbl {
            get {
                return ResourceManager.GetString("mwrs_save_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string mwrs_setrace_btn {
            get {
                return ResourceManager.GetString("mwrs_setrace_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start num..
        /// </summary>
        internal static string mwrs_StartNumber {
            get {
                return ResourceManager.GetString("mwrs_StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string mwrs_state_lbl {
            get {
                return ResourceManager.GetString("mwrs_state_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string mwrs_time_RacerInRace {
            get {
                return ResourceManager.GetString("mwrs_time_RacerInRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timekeepers.
        /// </summary>
        internal static string mwrs_timekeepers_lbl {
            get {
                return ResourceManager.GetString("mwrs_timekeepers_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string mwrs_title_label {
            get {
                return ResourceManager.GetString("mwrs_title_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track comissar.
        /// </summary>
        internal static string mwrs_trackcomis_lbl {
            get {
                return ResourceManager.GetString("mwrs_trackcomis_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string mwrs_user {
            get {
                return ResourceManager.GetString("mwrs_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string mwts_add_lbl_ {
            get {
                return ResourceManager.GetString("mwts_add_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tournament.
        /// </summary>
        internal static string mwts_add_new_btn {
            get {
                return ResourceManager.GetString("mwts_add_new_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add race.
        /// </summary>
        internal static string mwts_add_race_btn_ {
            get {
                return ResourceManager.GetString("mwts_add_race_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add race.
        /// </summary>
        internal static string mwts_addnewrace_lbl_ {
            get {
                return ResourceManager.GetString("mwts_addnewrace_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mwts_cancel_lbl {
            get {
                return ResourceManager.GetString("mwts_cancel_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mwts_cancel_lbl_ {
            get {
                return ResourceManager.GetString("mwts_cancel_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string mwts_cat_race_label_ {
            get {
                return ResourceManager.GetString("mwts_cat_race_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string mwts_cattour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_cattour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string mwts_choosetour_btn_ {
            get {
                return ResourceManager.GetString("mwts_choosetour_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose tour.
        /// </summary>
        internal static string mwts_choosetour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_choosetour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string mwts_date_race_lbl {
            get {
                return ResourceManager.GetString("mwts_date_race_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string mwts_datetour_header {
            get {
                return ResourceManager.GetString("mwts_datetour_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string mwts_delete_lbl_ {
            get {
                return ResourceManager.GetString("mwts_delete_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove race.
        /// </summary>
        internal static string mwts_delete_race_btn_ {
            get {
                return ResourceManager.GetString("mwts_delete_race_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght.
        /// </summary>
        internal static string mwts_lenghttour_header {
            get {
                return ResourceManager.GetString("mwts_lenghttour_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwts_name_race_lbl {
            get {
                return ResourceManager.GetString("mwts_name_race_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwts_nameracer_tour_lbl {
            get {
                return ResourceManager.GetString("mwts_nameracer_tour_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwts_nametour_header {
            get {
                return ResourceManager.GetString("mwts_nametour_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mwts_nametour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_nametour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laps.
        /// </summary>
        internal static string mwts_numoflapstour_header {
            get {
                return ResourceManager.GetString("mwts_numoflapstour_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. of racers.
        /// </summary>
        internal static string mwts_numofracerstour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_numofracerstour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. od races.
        /// </summary>
        internal static string mwts_numofracestour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_numofracestour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string mwts_place_race_lbl {
            get {
                return ResourceManager.GetString("mwts_place_race_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string mwts_placetour_header {
            get {
                return ResourceManager.GetString("mwts_placetour_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string mwts_pos_tour_lbl {
            get {
                return ResourceManager.GetString("mwts_pos_tour_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string mwts_race__info_lbl {
            get {
                return ResourceManager.GetString("mwts_race__info_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Num..
        /// </summary>
        internal static string mwts_race_num_info_lbl {
            get {
                return ResourceManager.GetString("mwts_race_num_info_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racers position.
        /// </summary>
        internal static string mwts_racerpostour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_racerpostour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string mwts_races_lbl_ {
            get {
                return ResourceManager.GetString("mwts_races_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string mwts_racestour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_racestour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string mwts_remove_lbl_ {
            get {
                return ResourceManager.GetString("mwts_remove_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mwts_save_lbl_ {
            get {
                return ResourceManager.GetString("mwts_save_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string mwts_score_tour_lbl {
            get {
                return ResourceManager.GetString("mwts_score_tour_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set tournament.
        /// </summary>
        internal static string mwts_settour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_settour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string mwts_shortname_lbl_ {
            get {
                return ResourceManager.GetString("mwts_shortname_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string mwts_state_race_lbl {
            get {
                return ResourceManager.GetString("mwts_state_race_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string mwts_team_tour_lbl {
            get {
                return ResourceManager.GetString("mwts_team_tour_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string mwts_timetour_header {
            get {
                return ResourceManager.GetString("mwts_timetour_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        internal static string mwts_title_label {
            get {
                return ResourceManager.GetString("mwts_title_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        internal static string mwts_tour_title {
            get {
                return ResourceManager.GetString("mwts_tour_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string mwts_yeartour_lbl_ {
            get {
                return ResourceManager.GetString("mwts_yeartour_lbl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string print_btn_ {
            get {
                return ResourceManager.GetString("print_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to database.
        /// </summary>
        internal static string pw_connectdbs_btn_ {
            get {
                return ResourceManager.GetString("pw_connectdbs_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string pw_connectdbs_label_ {
            get {
                return ResourceManager.GetString("pw_connectdbs_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        internal static string pw_keep_label_ {
            get {
                return ResourceManager.GetString("pw_keep_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string pw_password_label_ {
            get {
                return ResourceManager.GetString("pw_password_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string pw_port_label_ {
            get {
                return ResourceManager.GetString("pw_port_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string pw_serverdb_label_ {
            get {
                return ResourceManager.GetString("pw_serverdb_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string pw_user_label_ {
            get {
                return ResourceManager.GetString("pw_user_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string race_Addrace_title {
            get {
                return ResourceManager.GetString("race_Addrace_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string race_CarSelectRacer_label_ {
            get {
                return ResourceManager.GetString("race_CarSelectRacer_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string race_cat_race_label_ {
            get {
                return ResourceManager.GetString("race_cat_race_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laps.
        /// </summary>
        internal static string race_laps_race_label__ {
            get {
                return ResourceManager.GetString("race_laps_race_label__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string race_LoginTimekeeper_head {
            get {
                return ResourceManager.GetString("race_LoginTimekeeper_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string race_name_timekeep_lbl {
            get {
                return ResourceManager.GetString("race_name_timekeep_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string race_note_race_label_ {
            get {
                return ResourceManager.GetString("race_note_race_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string race_place_timekeep_lbl {
            get {
                return ResourceManager.GetString("race_place_timekeep_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string race_Position_label_ {
            get {
                return ResourceManager.GetString("race_Position_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference time.
        /// </summary>
        internal static string race_RefTimeSelectRacer_label_ {
            get {
                return ResourceManager.GetString("race_RefTimeSelectRacer_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string race_RoleTimekeeper_head {
            get {
                return ResourceManager.GetString("race_RoleTimekeeper_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racer status.
        /// </summary>
        internal static string race_StatusSelectRacer_label_ {
            get {
                return ResourceManager.GetString("race_StatusSelectRacer_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string race_time_race_label_ {
            get {
                return ResourceManager.GetString("race_time_race_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time keepers.
        /// </summary>
        internal static string race_timekeepers_lbl {
            get {
                return ResourceManager.GetString("race_timekeepers_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add timekeeper.
        /// </summary>
        internal static string racer_add_timekeeper_btn_ {
            get {
                return ResourceManager.GetString("racer_add_timekeeper_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add racer.
        /// </summary>
        internal static string racer_addracers_btn_ {
            get {
                return ResourceManager.GetString("racer_addracers_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string racer_AddressRacer_head {
            get {
                return ResourceManager.GetString("racer_AddressRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born.
        /// </summary>
        internal static string racer_BornRacer_head {
            get {
                return ResourceManager.GetString("racer_BornRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string racer_cancel_racer_btn_ {
            get {
                return ResourceManager.GetString("racer_cancel_racer_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string racer_closeracers_btn_ {
            get {
                return ResourceManager.GetString("racer_closeracers_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string racer_CompanynameTimekeeper_head {
            get {
                return ResourceManager.GetString("racer_CompanynameTimekeeper_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string racer_delete_racer_btn_ {
            get {
                return ResourceManager.GetString("racer_delete_racer_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove timekeeper.
        /// </summary>
        internal static string racer_delete_timekeeper_btn_ {
            get {
                return ResourceManager.GetString("racer_delete_timekeeper_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string racer_First_nameRacer_head {
            get {
                return ResourceManager.GetString("racer_First_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string racer_First_nameTimekeeper_head {
            get {
                return ResourceManager.GetString("racer_First_nameTimekeeper_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string racer_GenderRacer_head {
            get {
                return ResourceManager.GetString("racer_GenderRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string racer_Last_nameRacer_head {
            get {
                return ResourceManager.GetString("racer_Last_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string racer_Last_nameTimekeeper_head {
            get {
                return ResourceManager.GetString("racer_Last_nameTimekeeper_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string racer_MailRacer_head {
            get {
                return ResourceManager.GetString("racer_MailRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string racer_NationalityRacer_head {
            get {
                return ResourceManager.GetString("racer_NationalityRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racer.
        /// </summary>
        internal static string racer_Racer_Title {
            get {
                return ResourceManager.GetString("racer_Racer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racers.
        /// </summary>
        internal static string racer_racers_title {
            get {
                return ResourceManager.GetString("racer_racers_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string racer_save_racer_btn_ {
            get {
                return ResourceManager.GetString("racer_save_racer_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string racer_Short_nameRacer_head {
            get {
                return ResourceManager.GetString("racer_Short_nameRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string racer_TeamRacer_head {
            get {
                return ResourceManager.GetString("racer_TeamRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string racer_TelRacer_head {
            get {
                return ResourceManager.GetString("racer_TelRacer_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select race.
        /// </summary>
        internal static string RepMW_Events_Races_MenuItemHeader {
            get {
                return ResourceManager.GetString("RepMW_Events_Races_MenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string t_addTour_ {
            get {
                return ResourceManager.GetString("t_addTour_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string t_Category_head {
            get {
                return ResourceManager.GetString("t_Category_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string t_closeTour_ {
            get {
                return ResourceManager.GetString("t_closeTour_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string t_Name_head {
            get {
                return ResourceManager.GetString("t_Name_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. of racers.
        /// </summary>
        internal static string t_NumOfRacers_head {
            get {
                return ResourceManager.GetString("t_NumOfRacers_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. of racers.
        /// </summary>
        internal static string t_NumOfRaces_head {
            get {
                return ResourceManager.GetString("t_NumOfRaces_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string t_ShortName_head {
            get {
                return ResourceManager.GetString("t_ShortName_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        internal static string t_tournaments_title {
            get {
                return ResourceManager.GetString("t_tournaments_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string t_Year_head {
            get {
                return ResourceManager.GetString("t_Year_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racer.
        /// </summary>
        internal static string TC_Racer_label_ {
            get {
                return ResourceManager.GetString("TC_Racer_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Collection.
        /// </summary>
        internal static string TC_timecollection {
            get {
                return ResourceManager.GetString("TC_timecollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add team.
        /// </summary>
        internal static string team_addteam_btn_ {
            get {
                return ResourceManager.GetString("team_addteam_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string team_closeteam_btn_ {
            get {
                return ResourceManager.GetString("team_closeteam_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string team_email_head {
            get {
                return ResourceManager.GetString("team_email_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string team_shortname_head {
            get {
                return ResourceManager.GetString("team_shortname_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string team_teamname_head {
            get {
                return ResourceManager.GetString("team_teamname_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string team_teams_title {
            get {
                return ResourceManager.GetString("team_teams_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add record.
        /// </summary>
        internal static string TK_AddRecord_btn {
            get {
                return ResourceManager.GetString("TK_AddRecord_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string TK_Car_label_ {
            get {
                return ResourceManager.GetString("TK_Car_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string TK_choose_race_btn_ {
            get {
                return ResourceManager.GetString("TK_choose_race_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racer detail.
        /// </summary>
        internal static string TK_detail_racer_btn_ {
            get {
                return ResourceManager.GetString("TK_detail_racer_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament detail.
        /// </summary>
        internal static string TK_detail_tour_btn_ {
            get {
                return ResourceManager.GetString("TK_detail_tour_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final time.
        /// </summary>
        internal static string TK_FinalTimeKeeping_label_ {
            get {
                return ResourceManager.GetString("TK_FinalTimeKeeping_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racer.
        /// </summary>
        internal static string TK_Fullname_header {
            get {
                return ResourceManager.GetString("TK_Fullname_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap.
        /// </summary>
        internal static string TK_LapKeeping_header {
            get {
                return ResourceManager.GetString("TK_LapKeeping_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap.
        /// </summary>
        internal static string TK_LapKeeping_label_ {
            get {
                return ResourceManager.GetString("TK_LapKeeping_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string TK_NoteKeeping_label_ {
            get {
                return ResourceManager.GetString("TK_NoteKeeping_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paddock.
        /// </summary>
        internal static string TK_Paddock_Title {
            get {
                return ResourceManager.GetString("TK_Paddock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalization.
        /// </summary>
        internal static string TK_PenalizationKeeping_label_ {
            get {
                return ResourceManager.GetString("TK_PenalizationKeeping_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeping station.
        /// </summary>
        internal static string TK_Positionkeeper_header {
            get {
                return ResourceManager.GetString("TK_Positionkeeper_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        internal static string TK_Rep_Title {
            get {
                return ResourceManager.GetString("TK_Rep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all racers.
        /// </summary>
        internal static string TK_SelectAll_label_ {
            get {
                return ResourceManager.GetString("TK_SelectAll_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timekeeper.
        /// </summary>
        internal static string TK_TimeKeeper_header {
            get {
                return ResourceManager.GetString("TK_TimeKeeper_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TK_TimeKeeping_label_ {
            get {
                return ResourceManager.GetString("TK_TimeKeeping_label_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time keeping.
        /// </summary>
        internal static string TK_timekeeping_title {
            get {
                return ResourceManager.GetString("TK_timekeeping_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string user_active {
            get {
                return ResourceManager.GetString("user_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string user_active_head {
            get {
                return ResourceManager.GetString("user_active_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string user_adduser_btn_ {
            get {
                return ResourceManager.GetString("user_adduser_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user to brand.
        /// </summary>
        internal static string user_AddUserToBrand {
            get {
                return ResourceManager.GetString("user_AddUserToBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string user_closeuser_btn_ {
            get {
                return ResourceManager.GetString("user_closeuser_btn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string user_email_head {
            get {
                return ResourceManager.GetString("user_email_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string user_lastname_head {
            get {
                return ResourceManager.GetString("user_lastname_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string user_login_head {
            get {
                return ResourceManager.GetString("user_login_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string user_name_head {
            get {
                return ResourceManager.GetString("user_name_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string user_newpass_user_label {
            get {
                return ResourceManager.GetString("user_newpass_user_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string user_RemUserToBrand {
            get {
                return ResourceManager.GetString("user_RemUserToBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string user_role_head {
            get {
                return ResourceManager.GetString("user_role_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string user_save_user_btn {
            get {
                return ResourceManager.GetString("user_save_user_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user_user_title {
            get {
                return ResourceManager.GetString("user_user_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string user_users_title {
            get {
                return ResourceManager.GetString("user_users_title", resourceCulture);
            }
        }
    }
}
